### ISSUE TITLE
Change request: add support for Series: metadata

### ISSUE THREAD

**Issue by tooh** [mirzal/pelican-metadata-generator#1]
Support for metadata from Series plugin

**Comment by mirekdlugosz** [comment]
I am not very familiar with Series plugin. What kind of metadata does it have and how should this plugin use it?

Do you think this is something that reasonable user of Series plugin would like to turn on or off?

Also, would you be able to test the PR version to verify it is correct and what you had in mind before the release?

**Comment by tooh** [comment]
Thanks for the quick response.

The series plugin looks for a metadata Series: [name of series]

The rfc would be to optionally add this and when adding it to show the options from already present series names in other articles.

Of course I am prepared to test.

NB:

I recently found your project.

I restarted my use of pelican and are creating my environment.

Could be that I have some more rfc's.

Are you still using it yourself?

**Comment by mirekdlugosz** [comment]
Looking at the series plugin README, that should be relatively straightforward addition. I imagine it will come with a number of new settings, because some people might put series prefix in post title manually (and want series only for organization), and there are multiple ways you might want to display that.

I will notify you in the PR and we might continue there.

Yes, I still use the plugin on my own website.

**Comment by mirekdlugosz** [comment]
I just opened #2 with a change. As far as I can tell, it works, and behaves consistently with the rest of the program - i.e. you can type into field to create new series, or you can select one from a list. Input field and list overwrite each other, i.e. the last one sets series for a new post. Since I imagine most users will have posts that are not part of any series, there is no default value set, even if you have series already.

Please try it out and let me know what you think.

Also, I see my previous comments could have been a little misleading and confusing. I thought we are talking about https://github.com/mirekdlugosz/pelican-social-cards , which is my plugin for Pelican. But the general answer stands - I still use that tool, yes.

**Comment by tooh** [comment]
Thx, I have tomorrow some time to test.

Can you please hint how I can install this fix.

I'm familiar with github to download/clone full release.

Btw : during evaluation I tried to give a directory as the start argument.

I'm not sure which path this should be, the content directory or the content/articles ? Whatever I try I get an error. Without an argument the app starts up OK

**Comment by mirekdlugosz** [comment]
In command line, you would need something like below; adding comments with quick explanations what each thing does, so if you are using different tooling, adjust accordingly:

```bash
# clone repository
git clone https://github.com/mirekdlugosz/pelican-metadata-generator.git
# go to cloned repository
cd pelican-metadata-generator/
# switch to PR branch
git checkout support-series
# create virtual environment for a project - last argument is path
python3.11 -m venv .venv
# activate virtual environment
. .venv/bin/activate
# install poetry
pip install poetry
# install the tool in virtual environment
poetry install
# run the tool
poetry run pelican-metadata-generator -d /path/to/pelican/directory/
```

Pelican directory is an argument to `-d` option, not a positional parameter. If you tried something like `pelican-metadata-generator /path/to/pelican/`, it won't work - you need `-d` between program name and path.

If that was not the issue, could you paste here how you start a program and what error do you get? You can also pass `-v` flag to increase amount of things displayed in terminal, up to `-vvvvv`.

You should pass a path to `content` directory of your Pelican website. Path must be a directory - passing a path to specific file(s) won't work.

**Comment by tooh** [comment]
Thanks for your instructions. Some things are new to me f.i. poetry.

Followed your steps and created my test environment.

Series feature works as expected.  Releasable I think.

BTW During testing I noticed some things not related to the series feature. I will create separate issues.

<img width="799" alt="Screenshot 2024-02-19 at 13 28 31" src="https://github.com/mirekdlugosz/pelican-metadata-generator/assets/429386/8352a092-2e96-4864-804d-e5a0181b83c0">
