### ISSUE TITLE
RFC: option to assemble title/slug with YY-MM-DD-{title} 

### ISSUE THREAD

**Issue by tooh** [mirzal/pelican-metadata-generator#3]
I am used to prefix all my post filenames with the creation date in format YYYY-MM-DD

So no creation time.

**Comment by mirekdlugosz** [comment]
That sounds reasonable.

Done in https://github.com/mirekdlugosz/pelican-metadata-generator/commit/1017737c2540881e63f09a20b6afef1d14c514cf .

I imagine people might have various preferences for file names, so instead of simple "prepend with date", there's a new command line flag that allows you to set output file name template.

[`format()`](https://docs.python.org/3/library/stdtypes.html#str.format) will be called on template. Please see [Format String Syntax](https://docs.python.org/3/library/string.html#formatstrings) for all the details what Python supports.

For now template recognizes all the created date components (year, month, day, hour, minute, second), category, slug and file extension ([source](https://github.com/mirekdlugosz/pelican-metadata-generator/commit/1017737c2540881e63f09a20b6afef1d14c514cf#diff-3b6831bb9d23eecc7ceaefd2a68a3fac5887856a767eace4d40345996a003d9bR61)). I guess some people might want modified date, title or author as well? Hard to tell, we can deal with that if there's a request.

For now this can only be set during program start up, and only through command line flag. Perhaps there could be UI for that, but that would require new UI components, ideally some validation (to notify user they made a mistake by entering unrecognized tokens), and to be really usable also some way to persist it across program runs - and we would need a configuration file for that. That's way more than I want to do. Of course I will review pull requests adding these.

In your specific case, you will want to start a program like that:

```
pelican-metadata-generator -d /path/to/pelican/content/ --filename-template="{year}-{month:02}-{day:02}-{slug}.{ext}"
```

I will make a new release later today.
